[package]
name = "gcstat"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.1.6", default-features = false, features = ["std", "derive", "color"] }
rust-htslib = "0.38.2"
